# NOTE: ImageNet-22K (IN22k) dataloader is not implemented
# please implement IN22k data loader based on your data
# storage format, and update the paths in your config
# to load from your IN22k dataset.
data:
  dataset: cag
  batch_size: 16 #32
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: 
  num_workers: 10
  pin_mem: true
  root_path: /home/alatar/miacag/data/angio/
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: /home/alatar/ijepa/ijepa/logs
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 14
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_small
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 1
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 3
  weight_decay: 0.04


query: "SELECT * FROM ?schema_name.?table_name WHERE phase IS DISTINCT FROM 'test';"
query_pred: "SELECT * FROM ?schema_name.?table_name WHERE phase IS DISTINCT FROM 'test';"

query_transform: "SELECT * FROM ?schema_name.?table_name;"
query_split: "SELECT * FROM ?schema_name.?table_name WHERE phase IS DISTINCT FROM 'test';"

query_test: "SELECT * FROM ?schema_name.?table_name;"
query_train_plot: "SELECT * FROM ?schema_name.?table_name WHERE (phase = 'train')"
#query_train_plot: "SELECT * FROM ?schema_name.?table_name WHERE (phase = 'train') AND (\"ffr_proc_1_prox_rca\" IS NOT NULL)"

query_val_plot: "SELECT * FROM ?schema_name.?table_name WHERE (phase = 'val');"
query_test_plot: "SELECT * FROM ?schema_name.?table_name WHERE (phase = 'test');"

schema_name: "cag"
table_name: "dicom_table2x"
TestSize: 0.2

query_count_stenosis_train: "SELECT * FROM ?schema_name.?table_name WHERE (phase = 'train');"

query_count_stenosis_val: "SELECT * FROM ?schema_name.?table_name WHERE (phase = 'val');"

query_count_stenosis_test: "SELECT * FROM ?schema_name.?table_name WHERE (phase = 'test');"

# postgres configs
username: 'alatar'
password: '123qweasd'
database: 'mydb'
host: "localhost"